services:
  postgres:
    image: postgres:latest
    container_name: postgres_jira
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ejecutar-scripts:
    build:
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - postgres
    volumes:
      - ./:/app
    working_dir: /app
    tty: true         # Esto permite una terminal interactiva
    stdin_open: true  # Esto permite entrada por teclado
    command: ["bash"] # Arranca con bash en lugar de ejecutar algo directamente

volumes:
  pgdata:
